spring.application.name=spring-intro

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/book_store}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Bonchik12_}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.servlet.context-path=/api

jwt.secret=${JWT_SECRET:helloabcdelongkeysdfkmdslkfdsiljfsidl}
jwt.expiration=${JWT_EXPIRATION:3000000}
